[package]
name = "wordle-game-io"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
gmeta.workspace = true
gstd.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true

